// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlD2NQLC0laAmKKx3b1E8sWKRds0U8WO4',
    appId: '1:158378493020:web:d7300b8fa7231b9a13d299',
    messagingSenderId: '158378493020',
    projectId: 'fir-auth-2be20',
    authDomain: 'fir-auth-2be20.firebaseapp.com',
    storageBucket: 'fir-auth-2be20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNLBHSqGC2Do3DkODT_tMa1La_2HvO-4',
    appId: '1:158378493020:android:30eedabe2d180dd513d299',
    messagingSenderId: '158378493020',
    projectId: 'fir-auth-2be20',
    storageBucket: 'fir-auth-2be20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPFNp0-IyzmioLgcNwi5W4w2EbQIphcw',
    appId: '1:158378493020:ios:24672332ab34465813d299',
    messagingSenderId: '158378493020',
    projectId: 'fir-auth-2be20',
    storageBucket: 'fir-auth-2be20.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbPFNp0-IyzmioLgcNwi5W4w2EbQIphcw',
    appId: '1:158378493020:ios:24672332ab34465813d299',
    messagingSenderId: '158378493020',
    projectId: 'fir-auth-2be20',
    storageBucket: 'fir-auth-2be20.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlD2NQLC0laAmKKx3b1E8sWKRds0U8WO4',
    appId: '1:158378493020:web:f5a51424f0af1ece13d299',
    messagingSenderId: '158378493020',
    projectId: 'fir-auth-2be20',
    authDomain: 'fir-auth-2be20.firebaseapp.com',
    storageBucket: 'fir-auth-2be20.firebasestorage.app',
  );

}